services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: always
    network_mode: "host"
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TZ}
    volumes:
      - /var/lib/plexmediaserver:/config
      - /mnt/data/media:/data
      - /tmp:/transcode
  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plex-auto-languages
    network_mode: "host"
    restart: always
    environment:
      - PLEX_TOKEN=${X_PLEX_TOKEN}
      - TZ=${TZ}
    volumes:
      - ./plex-auto-languages:/config
