services:
  calibre:
    image: linuxserver/calibre:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    volumes:
      - /var/lib/config/calibre:/config
      - /mnt/data/media/Books:/data
    restart: unless-stopped
    
