services:
  caddy:
    container_name: caddy
    build: .
    restart: unless-stopped
    ports:
      - "30000:30000"  # qbittorrent
      - "4747:4747"  # servatrice
      - "4748:4748"  # servatrice
      - "25600:25600"  # komga
      - "20000:20000"  # netdata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./certs:/root/certs
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./conf.d/:/etc/caddy/conf.d
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?error}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?error}
      - AWS_REGION=${AWS_REGION:?error}
    networks:
      - anorak

networks:
  anorak:
    driver: bridge
    name: anorak

volumes:
  caddy_data:
  caddy_config:
