services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./conf.d/:/etc/caddy/conf.d
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - AWS_ACCES_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
volumes:
  caddy_data:
  caddy_config:
